### ISSUE TITLE
Discord Notifications with an apostrophe in the message will have random characters in place of it.

### ISSUE THREAD

**Issue by eggsnpie** [flathub/com.discordapp.Discord#357]
When I receive a notification of a message from the Discord flatpak that has an apostrophe in the message, the apostrophe will be replaced by a few random characters. Here's an example of a message I would receive: Why isn't Discord considered the greatest app ever?" When I receive the notification for this message, it will display the message as "Why isn#$39t Discord considered the greatest app ever?" 

Below, I've attached a screenshot of this happening with a message from a friend. The first image is of the message I received from the friend. The second image is of the notification I received for that message.

![Screenshot from 2023-12-27 07-32-08](https://github.com/flathub/com.discordapp.Discord/assets/152566041/918de5f1-c2dc-4b09-b089-142284674cf3)

![Screenshot from 2023-12-27 07-28-47](https://github.com/flathub/com.discordapp.Discord/assets/152566041/76b145a0-2382-497a-8b31-1ef33731465a)

**Comment by Sowgro** [comment]
I have the same issue

**Comment by SingularityCat** [comment]
These aren't random - they're HTML character entities. `&#39;` becomes `'`. (39 is the numeric ASCII code for `'`)
Discord isn't properly decoding the message (which is probably a HTML fragment) before passing it to notify-send.

**Comment by eggsnpie** [comment]
Interesting. Well, hopefully this should be a simple fix for the devs then.

**Comment by guihkx** [comment]
I do not see this issue with latest Discord on Plasma 6.1.5:

![image](https://github.com/user-attachments/assets/1374a7cb-d93f-4218-91b6-9ee3349ca0a8)

Maybe this has been fixed with recent updates, or maybe it's an issue specific to GNOME.

Either way, I don't think there's an issue with this Flatpak package, so I'm closing this.

**Comment by eggsnpie** [comment]
Yep. I forgot to close this issue myself a while ago. It has been fine as of recently.

**Comment by eucharistia** [comment]
I still have this issue no matter how I install Discord on Ubuntu 24.04.1

**Comment by guihkx** [comment]
@eucharistia Ubuntu 24.04 is still on GNOME Shell 46.0, and what appears to be [the fix for this issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/7f476e051cce72ec92c8c041eef485f82108eb0f), was only included in GNOME Shell 46.1 onward.
